import {
  LayoutDashboard,
  ConciergeBell,
  UtensilsCrossed,
  Sparkles,
  Package,
  Users,
  Calculator,
  Megaphone,
  Wrench,
} from "lucide-react";

export const navigation = [
  {
    title: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
  },
  {
    title: "Front Office",
    icon: ConciergeBell,
    children: [
      {
        title: "Reservations",
        children: [
          { title: "Room Booking", href: "/front-office/reservations/room-booking" },
          { title: "Company Master", href: "/front-office/reservations/company-master" },
          // { title: "Booking Type Master", href: "/front-office/reservations/booking-type-master" },
          // { title: "Booking Source Master", href: "/front-office/reservations/booking-source-master" },
          // { title: "Room Charges Master", href: "/front-office/reservations/room-charges-master" },
          // { title: "Promo Codes", href: "/front-office/reservations/promo-codes" },
          // { title: "Active / Inactive", href: "/front-office/reservations/active-inactive" },
          { title: "Booking Type Master", href: "#" },
          { title: "Booking Source Master", href: "#" },
          { title: "Room Charges Master", href: "#" },
          { title: "Promo Codes", href: "#" },
          { title: "Active / Inactive", href: "#" },
        ],
      },
      // { title: "Guest List", href: "/front-office/guest-list" },
      // { title: "Today's Arrivals", href: "/front-office/todays-arrivals" },
      // { title: "Check In", href: "/front-office/check-in" },
      { title: "Guest List", href: "#" },
      { title: "Today's Arrivals", href: "#" },
      { title: "Check In", href: "#" },
      {
        title: "Check Out",
        children: [
          // { title: "Room Check Out", href: "/front-office/check-out/room-check-out" },
          // { title: "Pax Check Out", href: "/front-office/check-out/pax-check-out" },
          // { title: "Split Folio", href: "/front-office/check-out/split-folio" },
          // { title: "Settlement", href: "/front-office/check-out/settlement" },
          { title: "Room Check Out", href: "#" },
          { title: "Pax Check Out", href: "#" },
          { title: "Split Folio", href: "#" },
          { title: "Settlement", href: "#" },
        ],
      },
      // { title: "Room Status", href: "/front-office/room-status" },
      // { title: "Room Charges Postings", href: "/front-office/room-charges-postings" },
      // { title: "Payment Postings", href: "/front-office/payment-postings" },
      { title: "Room Status", href: "#" },
      { title: "Room Charges Postings", href: "#" },
      { title: "Payment Postings", href: "#" },
      {
        title: "Reports",
        children: [
          // { title: "Arrivals", href: "/front-office/reports/arrivals" },
          // { title: "Departures", href: "/front-office/reports/departures" },
          // { title: "In-House", href: "/front-office/reports/in-house" },
          // { title: "Cancelled", href: "/front-office/reports/cancelled" },
          // { title: "Unexpected Departures", href: "/front-office/reports/unexpected-departures" },
          // { title: "Postings Report", href: "/front-office/reports/postings" },
          // { title: "Cashier's Report", href: "/front-office/reports/cashiers-report" },
          { title: "Arrivals", href: "#" },
          { title: "Departures", href: "/front-office/reports/departures" },
          { title: "In-House", href: "/front-office/reports/in-house" },
          { title: "Cancelled", href: "/front-office/reports/cancelled" },
          { title: "Unexpected Departures", href: "/front-office/reports/unexpected-departures" },
          { title: "Postings Report", href: "/front-office/reports/postings" },
          { title: "Cashier's Report", href: "/front-office/reports/cashiers-report" },
        ],
      },
      // { title: "Cashier's Closing", href: "/front-office/cashiers-closing" },
      // { title: "Day Closing", href: "/front-office/day-closing" },
      { title: "Cashier's Closing", href: "#" },
      { title: "Day Closing", href: "#" },
    ],
  },
  {
    title: "Food & Beverages",
    icon: UtensilsCrossed,
    children: [
      {
        title: "Restaurant #1",
        children: [
          // { title: "New Table", href: "/fnb/restaurant-1/new-table" },
          // { title: "Table Status", href: "/fnb/restaurant-1/table-status" },
          // { title: "Cashier's Report", href: "/fnb/restaurant-1/cashiers-report" },
          // { title: "Cashier's Closing", href: "/fnb/restaurant-1/cashiers-closing" },
          // { title: "Day Close", href: "/fnb/restaurant-1/day-close" },
          { title: "New Table", href: "#" },
          { title: "Table Status", href: "#" },
          { title: "Cashier's Report", href: "#" },
          { title: "Cashier's Closing", href: "#" },
          { title: "Day Close", href: "#" },
        ],
      },
      {
        title: "Restaurant #2",
        children: [
            // { title: "New Table", href: "/fnb/restaurant-2/new-table" },
            // { title: "Table Status", href: "/fnb/restaurant-2/table-status" },
            // { title: "Cashier's Report", href: "/fnb/restaurant-2/cashiers-report" },
            // { title: "Cashier's Closing", href: "/fnb/restaurant-2/cashiers-closing" },
            // { title: "Day Close", href: "/fnb/restaurant-2/day-close" },
            { title: "New Table", href: "#" },
            { title: "Table Status", href: "#" },
            { title: "Cashier's Report", href: "#" },
            { title: "Cashier's Closing", href: "#" },
            { title: "Day Close", href: "#" },
        ],
      },
      {
        title: "Conference Room #1",
        children: [
          // { title: "Hall Booking List", href: "/fnb/conference-room-1/bookings" },
          // { title: "Menu Posting", href: "/fnb/conference-room-1/menu-posting" },
          // { title: "Conference Requirement", href: "/fnb/conference-room-1/conference-requirement" },
          // { title: "Close Booking", href: "/fnb/conference-room-1/close-booking" },
          { title: "Hall Booking List", href: "#" },
          { title: "Menu Posting", href: "#" },
          { title: "Conference Requirement", href: "#" },
          { title: "Close Booking", href: "#" },
        ],
      },
      {
        title: "Conference Room #2",
        children: [
          // { title: "Hall Booking List", href: "/fnb/conference-room-2/bookings" },
          // { title: "Menu Posting", href: "/fnb/conference-room-2/menu-posting" },
          // { title: "Conference Requirement", href: "/fnb/conference-room-2/conference-requirement" },
          // { title: "Close Booking", href: "/fnb/conference-room-2/close-booking" },
          { title: "Hall Booking List", href: "#" },
          { title: "Menu Posting", href: "#" },
          { title: "Conference Requirement", href: "#" },
          { title: "Close Booking", href: "#" },
        ],
      },
      {
        title: "Lawn",
        children: [
          // { title: "Hall Booking List", href: "/fnb/lawn/bookings" },
          // { title: "Menu Posting", href: "/fnb/lawn/menu-posting" },
          // { title: "Conference Requirement", href: "/fnb/lawn/conference-requirement" },
          // { title: "Close Booking", href: "/fnb/lawn/close-booking" },
          { title: "Hall Booking List", href: "#" },
          { title: "Menu Posting", href: "#" },
          { title: "Conference Requirement", href: "#" },
          { title: "Close Booking", href: "#" },
        ],
      },
      ...["main-kitchen", "indian-kitchen", "continental-kitchen", "italian-kitchen"].map((kitchen) => ({
        title: kitchen.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" "),
        children: [
          // { title: "Food Category", href: `/fnb/kitchen/${kitchen}/food-category` },
          // { title: "Food Items", href: `/fnb/kitchen/${kitchen}/food-items` },
          // { title: "Food List", href: `/fnb/kitchen/${kitchen}/food-list` },
          // { title: "Manage Add-Ons", href: `/fnb/kitchen/${kitchen}/manage-add-ons` },
          // { title: "Create Requisition", href: `/fnb/kitchen/${kitchen}/create-requisition` },
          // { title: "Spoilage / Breakage", href: `/fnb/kitchen/${kitchen}/spoilage-breakage` },
          // { title: "Stock Movement", href: `/fnb/kitchen/${kitchen}/stock-movement` },
          { title: "Food Category", href: "#" },
          { title: "Food Items", href: "#" },
          { title: "Food List", href: "#" },
          { title: "Manage Add-Ons", href: "#" },
          { title: "Create Requisition", href: "#" },
          { title: "Spoilage / Breakage", href: "#" },
          { title: "Stock Movement", href: "#" },
        ],
      })),
      {
        title: "BAR",
        children: [
          // { title: "Beverage Category", href: "/fnb/bar/beverage-category" },
          // { title: "Bar Items", href: "/fnb/bar/bar-items" },
          // { title: "Bar List", href: "/fnb/bar/bar-list" },
          // { title: "Manage Add-Ons", href: "/fnb/bar/manage-add-ons" },
          // { title: "Create Requisition", href: "/fnb/bar/create-requisition" },
          // { title: "Spoilage / Breakage", href: "/fnb/bar/spoilage-breakage" },
          // { title: "Stock Movement", href: "/fnb/bar/stock-movement" },
          { title: "Beverage Category", href: "#" },
          { title: "Bar Items", href: "/fnb/bar/bar-items" },
          { title: "Bar List", href: "/fnb/bar/bar-list" },
          { title: "Manage Add-Ons", href: "/fnb/bar/manage-add-ons" },
          { title: "Create Requisition", href: "/fnb/bar/create-requisition" },
          { title: "Spoilage / Breakage", href: "/fnb/bar/spoilage-breakage" },
          { title: "Stock Movement", href: "/fnb/bar/stock-movement" },
        ],
      },
      {
        title: "F & B Controls",
        children: [
          // { title: "Food Inventory", href: "/fnb/controls/food-inventory" },
          // { title: "Beverage Inventory", href: "/fnb/controls/beverage-inventory" },
          // { title: "Stores Inventory", href: "/fnb/controls/stores-inventory" },
          // { title: "Spoilage Authorize", href: "/fnb/controls/spoilage-authorize" },
          // { title: "Stock Movement Authorize", href: "/fnb/controls/stock-movement-authorize" },
          // { title: "Food Costing", href: "/fnb/controls/food-costing" },
          // { title: "Beverage Costing", href: "/fnb/controls/beverage-costing" },
          { title: "Food Inventory", href: "#" },
          { title: "Beverage Inventory", href: "#" },
          { title: "Stores Inventory", href: "#" },
          { title: "Spoilage Authorize", href: "#" },
          { title: "Stock Movement Authorize", href: "#" },
          { title: "Food Costing", href: "#" },
          { title: "Beverage Costing", href: "#" },
        ],
      },
      {
        title: "Reports",
        children: [
          // { title: "Sales Report", href: "/fnb/reports/sales" },
          // { title: "Collection Report", href: "/fnb/reports/collection" },
          // { title: "Cost Reports", href: "/fnb/reports/cost" },
          // { title: "Inventory Report", href: "/fnb/reports/inventory" },
          // { title: "Spoilage / Breakage", href: "/fnb/reports/spoilage-breakage" },
          // { title: "Stock Movement", href: "/fnb/reports/stock-movement" },
          // { title: "Log Report", href: "/fnb/reports/log" },
          // { title: "Requisition Report", href: "/fnb/reports/requisition" },
          { title: "Sales Report", href: "#" },
          { title: "Collection Report", href: "#" },
          { title: "Cost Reports", href: "#" },
          { title: "Inventory Report", href: "#" },
          { title: "Spoilage / Breakage", href: "#" },
          { title: "Stock Movement", href: "#" },
          { title: "Log Report", href: "#" },
          { title: "Requisition Report", href: "#" },
        ],
      },
    ],
  },
  {
    title: "Housekeeping",
    icon: Sparkles,
    children: [
      { title: "Room Master", href: "/housekeeping/room-master" },
      { title: "Public Area Master", href: "/housekeeping/public-area-master" },
      { title: "Room Cleaning", href: "/housekeeping/room-cleaning" },
      { title: "Public Area Cleaning", href: "/housekeeping/public-area-cleaning" },
      { title: "Change Room Status", href: "/housekeeping/change-room-status" },
      { title: "Block Rooms", href: "/housekeeping/block-rooms" },
      { title: "Block Public Area", href: "/housekeeping/block-public-area" },
      { title: "Linen Movement", href: "/housekeeping/linen-movement" },
      { title: "Item Movement", href: "/housekeeping/item-movement" },
      { title: "Laundry List", href: "/housekeeping/laundry-list" },
      { title: "Linen Discards", href: "/housekeeping/linen-discards" },
      { title: "Create Requisition", href: "/housekeeping/create-requisition" },
      { title: "Reports", href: "/housekeeping/reports" },
    ],
  },
  {
    title: "Purchase & Stores",
    icon: Package,
    children: [
      { title: "Unit Master", href: "/purchase/unit-master" },
      { title: "Category Master", href: "/purchase/category-master" },
      { title: "Product Master", href: "/purchase/product-master" },
      { title: "Supplier Master", href: "/purchase/supplier-master" },
      { title: "Purchase Order", href: "/purchase/purchase-order" },
      { title: "Purchase Return", href: "/purchase/purchase-return" },
      { title: "Stock Register", href: "/purchase/stock-register" },
      { title: "Spoilage / Breakage", href: "/purchase/spoilage-breakage" },
      { title: "Par Stock Items", href: "/purchase/par-stock-items" },
      {
        title: "Reports",
        children: [
          { title: "Stock Register", href: "/purchase/reports/stock-register" },
          { title: "Purchase Report", href: "/purchase/reports/purchase" },
          { title: "Issues Report", href: "/purchase/reports/issues" },
          { title: "Par Stock Report", href: "/purchase/reports/par-stock" },
          { title: "Spoilage / Breakage", href: "/purchase/reports/spoilage-breakage" },
          { title: "Purchase Order Report", href: "/purchase/reports/purchase-order" },
          { title: "Purchase Return Report", href: "/purchase/reports/purchase-return" },
        ],
      },
    ],
  },
  {
    title: "Human Resource",
    href: "/human-resource",
    icon: Users,
  },
  {
    title: "Accounts",
    href: "/accounts",
    icon: Calculator,
  },
  {
    title: "Sales & Marketing",
    href: "/sales-marketing",
    icon: Megaphone,
  },
  {
    title: "Maintenance",
    href: "/maintenance",
    icon: Wrench,
  },
];

export function flattenNavItems(items = navigation, result = []) {
  for (const item of items) {
    if (item.href) result.push({ title: item.title, href: item.href });
    if (item.children) flattenNavItems(item.children, result);
  }
  return result;
}

export function findNavTitleByHref(href, items = navigation) {
  for (const item of items) {
    if (item.href === href) return item.title;
    if (item.children) {
      const found = findNavTitleByHref(href, item.children);
      if (found) return found;
    }
  }
  return null;
}
