import {
  reservationList,
  groupBookings,
  companies,
  bookingTypes,
  bookingSources,
  roomCharges,
  promoCodes,
  guests,
  inHouseGuests,
  todaysArrivals,
  rooms,
  availabilityCalendar,
  folioEntries,
  checkoutSummary,
  payments,
  invoices,
  postings,
  visitors,
  wakeUpCalls,
  luggageRecords,
  lostAndFound,
  hkRequests,
  maintRequests,
  guestFeedback,
  taxiBookings,
  messages,
  posOrders,
  checkInFormFields,
  checkInSections,
  pendingCheckIns,
  walkInFormFields,
  reservationFormSections,
} from "@/lib/data/front-office";

const reportColumns = [
  { key: "id", label: "ID" },
  { key: "date", label: "Date" },
  { key: "description", label: "Description" },
  { key: "amount", label: "Amount", type: "currency" },
  { key: "status", label: "Status", type: "status" },
];

const sampleReports = [
  { id: "RPT-001", date: "23 Jun 2026", description: "Sample report entry", amount: 15000, status: "Generated" },
  { id: "RPT-002", date: "22 Jun 2026", description: "Sample report entry", amount: 12500, status: "Generated" },
];

export const frontOfficePageConfigs = {
  // ─── Reservations ─────────────────────────────────────────────────────────
  "/front-office/reservations/new": {
    type: "reservation-form",
    title: "New Reservation",
    description: "Create a new reservation with guest details, booking info, and payment.",
    sections: reservationFormSections,
  },
  "/front-office/reservations/list": {
    type: "data-table",
    title: "Reservation List",
    description: "View and manage all reservations.",
    actions: ["View", "Edit", "Cancel", "Print", "Check-in"],
    filters: ["Date", "Room Type", "Status", "Source"],
    columns: [
      { key: "id", label: "Booking ID" },
      { key: "guestName", label: "Guest Name" },
      { key: "mobile", label: "Mobile" },
      { key: "room", label: "Room" },
      { key: "checkIn", label: "Check-in" },
      { key: "checkOut", label: "Check-out" },
      { key: "balance", label: "Balance", type: "currency" },
      { key: "status", label: "Status", type: "status" },
    ],
    data: reservationList,
  },
  "/front-office/reservations/walk-in": {
    type: "form",
    title: "Walk-in Guest",
    description: "Quick booking for walk-in guests.",
    formFields: walkInFormFields,
    actions: ["Check In"],
  },
  "/front-office/reservations/group-booking": {
    type: "data-table",
    title: "Group Booking",
    description: "Manage group and block reservations.",
    actions: ["New Group", "Edit", "Cancel"],
    columns: [
      { key: "id", label: "Group ID" },
      { key: "groupName", label: "Group Name" },
      { key: "contactPerson", label: "Contact" },
      { key: "rooms", label: "Rooms" },
      { key: "pax", label: "Pax" },
      { key: "checkIn", label: "Check-in" },
      { key: "checkOut", label: "Check-out" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "status", label: "Status", type: "status" },
    ],
    data: groupBookings,
  },
  "/front-office/reservations/todays-arrivals": {
    type: "data-table",
    title: "Today's Arrivals",
    description: "Expected arrivals with room allocation.",
    actions: ["Room Allocation", "Check-in"],
    columns: [
      { key: "id", label: "Booking ID" },
      { key: "guest", label: "Guest Name" },
      { key: "roomType", label: "Room Type" },
      { key: "roomNo", label: "Room No" },
      { key: "pax", label: "Pax" },
      { key: "eta", label: "ETA" },
      { key: "specialMessage", label: "Special Message" },
      { key: "allocation", label: "Allocation", type: "status" },
    ],
    data: todaysArrivals,
  },
  "/front-office/reservations/company-master": {
    type: "master-list",
    title: "Company Master",
    description: "Corporate accounts and billing.",
    formFields: ["Company Name", "Contact Person", "Address", "Email", "Contact Nos.", "Credit Allowed", "Credit Limit", "Settlement Type", "GST No.", "State"],
    columns: [
      { key: "id", label: "ID" }, { key: "name", label: "Company" }, { key: "contactPerson", label: "Contact" },
      { key: "email", label: "Email" }, { key: "phone", label: "Phone" }, { key: "creditAllowed", label: "Credit" },
      { key: "creditLimit", label: "Limit", type: "currency" }, { key: "status", label: "Status", type: "status" },
    ],
    data: companies,
  },
  "/front-office/reservations/booking-type-master": {
    type: "master-list",
    title: "Booking Type Master",
    columns: [{ key: "id", label: "ID" }, { key: "name", label: "Type" }, { key: "description", label: "Description" }, { key: "status", label: "Status", type: "status" }],
    data: bookingTypes,
  },
  "/front-office/reservations/booking-source-master": {
    type: "master-list",
    title: "Booking Source Master",
    columns: [{ key: "id", label: "ID" }, { key: "name", label: "Source" }, { key: "commission", label: "Commission" }, { key: "status", label: "Status", type: "status" }],
    data: bookingSources,
  },
  "/front-office/reservations/room-charges-master": {
    type: "master-list",
    title: "Room Charges Master",
    columns: [
      { key: "id", label: "ID" }, { key: "roomCategory", label: "Category" }, { key: "bedType", label: "Bed" },
      { key: "rackRate", label: "Rack", type: "currency" }, { key: "corporateRate", label: "Corporate", type: "currency" },
      { key: "status", label: "Status", type: "status" },
    ],
    data: roomCharges,
  },
  "/front-office/reservations/promo-codes": {
    type: "master-list",
    title: "Promo Codes",
    columns: [
      { key: "id", label: "ID" }, { key: "code", label: "Code" }, { key: "discount", label: "Discount" },
      { key: "validFrom", label: "From" }, { key: "validTo", label: "To" }, { key: "status", label: "Status", type: "status" },
    ],
    data: promoCodes,
  },

  // ─── Core Operations ──────────────────────────────────────────────────────
  "/front-office/check-in": {
    type: "check-in",
    title: "Check-In",
    description: "Guest verification, room allocation, ID upload, deposit, and key card.",
    sections: checkInSections,
    pendingCheckIns,
  },
  "/front-office/in-house-guests": {
    type: "data-table",
    title: "In-House Guests",
    description: "Currently checked-in guests.",
    actions: ["Add Service", "Change Room", "Extend Stay", "Print Bill", "Check Out"],
    columns: [
      { key: "guest", label: "Guest" }, { key: "room", label: "Room" }, { key: "checkIn", label: "Check-in" },
      { key: "nights", label: "Nights" }, { key: "balance", label: "Balance", type: "currency" },
      { key: "restaurantBill", label: "Restaurant", type: "currency" }, { key: "laundry", label: "Laundry", type: "currency" },
      { key: "status", label: "Status", type: "status" },
    ],
    data: inHouseGuests,
  },
  "/front-office/room-availability": {
    type: "availability",
    title: "Room Availability",
    description: "Calendar view of room occupancy.",
    calendar: availabilityCalendar,
  },
  "/front-office/room-status": {
    type: "room-grid",
    title: "Room Status",
    description: "Vacant, Occupied, Dirty, Clean, Maintenance, Blocked.",
    data: rooms,
    actions: ["Assign", "Move Room", "Block Room"],
  },
  "/front-office/guest-profiles": {
    type: "guest-profile",
    title: "Guest Profiles",
    description: "Complete guest history — personal, stays, invoices, loyalty.",
    guests,
  },
  "/front-office/guest-folio": {
    type: "folio",
    title: "Guest Folio",
    description: "Running account — debits, credits, and balance.",
    guestName: "James Wilson",
    roomNo: "112",
    columns: [
      { key: "date", label: "Date" }, { key: "description", label: "Description" },
      { key: "debit", label: "Debit", type: "currency" }, { key: "credit", label: "Credit", type: "currency" },
      { key: "balance", label: "Balance", type: "currency" },
    ],
    data: folioEntries,
  },
  "/front-office/payments": {
    type: "data-table",
    title: "Payments",
    description: "Payment history — Cash, UPI, Card, Bank, Split, Refund, Advance.",
    actions: ["New Payment", "Refund", "Split Payment"],
    columns: [
      { key: "id", label: "Payment ID" }, { key: "date", label: "Date" }, { key: "guest", label: "Guest" },
      { key: "roomNo", label: "Room" }, { key: "mode", label: "Mode" }, { key: "type", label: "Type" },
      { key: "amount", label: "Amount", type: "currency" }, { key: "reference", label: "Reference" },
    ],
    data: payments,
  },
  "/front-office/check-out": {
    type: "checkout",
    title: "Check-Out",
    description: "Checkout summary with room, F&B, laundry charges and settlement.",
    summary: checkoutSummary,
  },
  "/front-office/pos-billing": {
    type: "pos-billing",
    title: "POS Billing",
    description: "Restaurant billing for walk-in or in-house guests.",
    orders: posOrders,
  },

  // ─── Guest Services ───────────────────────────────────────────────────────
  "/front-office/room-transfer": {
    type: "form",
    title: "Room Transfer",
    description: "Move guest to a different room.",
    formFields: ["Guest Name", "Current Room", "New Room", "Reason", "Transfer Date"],
  },
  "/front-office/extend-stay": {
    type: "form",
    title: "Extend Stay",
    description: "Extend guest checkout with availability check.",
    formFields: ["Guest Name", "Room No", "Current Checkout", "New Checkout", "Extra Charges", "Availability"],
  },
  "/front-office/early-late-check": {
    type: "form",
    title: "Early Check-in / Late Check-out",
    description: "Early check-in or late checkout with charges and approval.",
    formFields: ["Guest Name", "Room No", "Type", "Charges", "Approval By", "Reason"],
  },
  "/front-office/visitor-management": {
    type: "data-table",
    title: "Visitor Management",
    description: "Visitor entry log.",
    actions: ["New Visitor", "Check Out Visitor"],
    columns: [
      { key: "id", label: "ID" }, { key: "visitorName", label: "Visitor" }, { key: "guestName", label: "Guest" },
      { key: "room", label: "Room" }, { key: "timeIn", label: "Time In" }, { key: "timeOut", label: "Time Out" },
      { key: "purpose", label: "Purpose" },
    ],
    data: visitors,
  },
  "/front-office/luggage-management": {
    type: "data-table",
    title: "Luggage Management",
    description: "Store and return guest luggage.",
    actions: ["Store Luggage", "Return Luggage"],
    columns: [
      { key: "id", label: "ID" }, { key: "guest", label: "Guest" }, { key: "bagCount", label: "Bags" },
      { key: "tokenNo", label: "Token" }, { key: "stored", label: "Stored" }, { key: "returned", label: "Returned" },
      { key: "status", label: "Status", type: "status" },
    ],
    data: luggageRecords,
  },
  "/front-office/wake-up-calls": {
    type: "data-table",
    title: "Wake-up Calls",
    description: "Schedule and track wake-up calls.",
    actions: ["New Wake-up Call", "Mark Completed"],
    columns: [
      { key: "id", label: "ID" }, { key: "guest", label: "Guest" }, { key: "room", label: "Room" },
      { key: "date", label: "Date" }, { key: "time", label: "Time" }, { key: "completed", label: "Status", type: "status" },
    ],
    data: wakeUpCalls,
  },
  "/front-office/housekeeping-requests": {
    type: "data-table",
    title: "Housekeeping Requests",
    description: "Guest housekeeping requests from front office.",
    actions: ["New Request", "Assign Staff"],
    columns: [
      { key: "id", label: "ID" }, { key: "guest", label: "Guest" }, { key: "room", label: "Room" },
      { key: "issue", label: "Issue" }, { key: "assignedStaff", label: "Staff" }, { key: "status", label: "Status", type: "status" },
    ],
    data: hkRequests,
  },
  "/front-office/maintenance-requests": {
    type: "data-table",
    title: "Maintenance Requests",
    description: "Room maintenance tickets.",
    actions: ["New Ticket", "Assign Engineer"],
    columns: [
      { key: "id", label: "ID" }, { key: "room", label: "Room" }, { key: "problem", label: "Problem" },
      { key: "priority", label: "Priority", type: "status" }, { key: "engineer", label: "Engineer" },
      { key: "status", label: "Status", type: "status" },
    ],
    data: maintRequests,
  },
  "/front-office/lost-and-found": {
    type: "data-table",
    title: "Lost & Found",
    description: "Track lost and found items.",
    actions: ["Add Item", "Mark Returned"],
    columns: [
      { key: "id", label: "ID" }, { key: "item", label: "Item" }, { key: "guest", label: "Guest" },
      { key: "foundBy", label: "Found By" }, { key: "room", label: "Room" },
      { key: "status", label: "Status", type: "status" }, { key: "returnedDate", label: "Returned" },
    ],
    data: lostAndFound,
  },
  "/front-office/guest-feedback": {
    type: "data-table",
    title: "Guest Feedback",
    description: "Ratings for cleanliness, food, and service.",
    columns: [
      { key: "id", label: "ID" }, { key: "guest", label: "Guest" }, { key: "rating", label: "Rating" },
      { key: "cleanliness", label: "Cleanliness" }, { key: "food", label: "Food" }, { key: "service", label: "Service" },
      { key: "date", label: "Date" },
    ],
    data: guestFeedback,
  },
  "/front-office/taxi-booking": {
    type: "data-table",
    title: "Taxi / Cab Booking",
    description: "Guest cab and taxi bookings.",
    actions: ["New Booking"],
    columns: [
      { key: "id", label: "ID" }, { key: "guest", label: "Guest" }, { key: "pickup", label: "Pickup" },
      { key: "drop", label: "Drop" }, { key: "driver", label: "Driver" }, { key: "vehicle", label: "Vehicle" },
      { key: "fare", label: "Fare", type: "currency" }, { key: "status", label: "Status", type: "status" },
    ],
    data: taxiBookings,
  },
  "/front-office/messages": {
    type: "data-table",
    title: "Messages",
    description: "Internal notes and guest messages.",
    actions: ["New Message", "Mark Read"],
    columns: [
      { key: "id", label: "ID" }, { key: "type", label: "Type" }, { key: "from", label: "From" },
      { key: "subject", label: "Subject" }, { key: "date", label: "Date" },
      { key: "read", label: "Read", type: "status" },
    ],
    data: messages.map((m) => ({ ...m, read: m.read ? "Read" : "Unread" })),
  },
  "/front-office/invoice-history": {
    type: "data-table",
    title: "Invoice History",
    description: "View, download, and email invoices.",
    actions: ["Download PDF", "Email Invoice"],
    columns: [
      { key: "id", label: "Invoice No" }, { key: "guest", label: "Guest" }, { key: "date", label: "Date" },
      { key: "subtotal", label: "Subtotal", type: "currency" }, { key: "gst", label: "GST", type: "currency" },
      { key: "grandTotal", label: "Total", type: "currency" }, { key: "payment", label: "Payment", type: "status" },
    ],
    data: invoices,
  },
  "/front-office/room-charges-postings": {
    type: "data-table",
    title: "Room Charges Postings",
    columns: [
      { key: "id", label: "ID" }, { key: "date", label: "Date" }, { key: "roomNo", label: "Room" },
      { key: "guest", label: "Guest" }, { key: "description", label: "Description" },
      { key: "amount", label: "Amount", type: "currency" },
    ],
    data: postings,
  },
  "/front-office/cashiers-closing": {
    type: "closing",
    title: "Cashier's Closing",
    formFields: ["Shift", "Opening Balance", "Cash", "Card", "UPI", "Closing Balance"],
  },
  "/front-office/day-closing": {
    type: "closing",
    title: "Day Closing",
    formFields: ["Business Date", "Total Revenue", "Occupancy %", "Arrivals", "Departures", "Remarks"],
  },
};

// Reports
const foReports = {
  "daily-arrival": "Daily Arrival Report",
  departures: "Departure Report",
  occupancy: "Occupancy Report",
  revenue: "Revenue Report",
  cashier: "Cashier Report",
  "night-audit": "Night Audit Report",
  guest: "Guest Report",
  room: "Room Report",
  tax: "Tax Report",
  arrivals: "Arrivals Report",
  "in-house": "In-House Report",
  cancelled: "Cancelled Report",
  postings: "Postings Report",
};

Object.entries(foReports).forEach(([key, title]) => {
  frontOfficePageConfigs[`/front-office/reports/${key}`] = {
    type: "report",
    title,
    description: title,
    columns: reportColumns,
    data: sampleReports,
  };
});

// Legacy route redirects (keep old URLs working)
frontOfficePageConfigs["/front-office/reservations/room-booking"] = frontOfficePageConfigs["/front-office/reservations/list"];
frontOfficePageConfigs["/front-office/guest-list"] = {
  type: "data-table",
  title: "Guest List",
  columns: [
    { key: "id", label: "Guest ID" }, { key: "name", label: "Name" }, { key: "mobile", label: "Mobile" },
    { key: "email", label: "Email" }, { key: "nationality", label: "Nationality" }, { key: "visits", label: "Visits" },
    { key: "lastStay", label: "Last Stay" },
  ],
  data: guests,
};
